{"uuid": "ef93212a-ad88-4f61-84ef-6283e4a8185b", "children": ["dfae734c-d809-4128-8f3b-152fbdb467fa"], "befores": [{"name": "get_value", "status": "broken", "statusDetails": {"message": "requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='movie.querydata.org', port=443): Read timed out. (read timeout=20)\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"F:\\pythoncode\\learn_pytest_20200720\\testcase\\test_api.py\", line 23, in get_value\n    par = dict(param, **famous_list())\n  File \"F:\\pythoncode\\learn_pytest_20200720\\unit\\middle_val.py\", line 14, in famous_list\n    init_relevance = ini_request(case_dict, PATH)\n  File \"F:\\pythoncode\\learn_pytest_20200720\\unit\\initializePremise.py\", line 24, in ini_request\n    i[\"address\"], _path,relevance_list)\n  File \"F:\\pythoncode\\learn_pytest_20200720\\unit\\apiSend.py\", line 86, in send_request\n    timeout=data[\"timeout\"])\n  File \"F:\\pythoncode\\learn_pytest_20200720\\unit\\apiMethod.py\", line 68, in get\n    response = requests.get(url=address, params=data, headers=header, timeout=timeout)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\api.py\", line 76, in get\n    return request('get', url, params=params, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\adapters.py\", line 529, in send\n    raise ReadTimeout(e, request=request)\n"}, "steps": [{"name": "接口关联请求", "status": "broken", "statusDetails": {"message": "requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='movie.querydata.org', port=443): Read timed out. (read timeout=20)\n", "trace": "  File \"F:\\pythoncode\\learn_pytest_20200720\\unit\\initializePremise.py\", line 24, in ini_request\n    i[\"address\"], _path,relevance_list)\n  File \"F:\\pythoncode\\learn_pytest_20200720\\unit\\apiSend.py\", line 86, in send_request\n    timeout=data[\"timeout\"])\n  File \"F:\\pythoncode\\learn_pytest_20200720\\unit\\apiMethod.py\", line 68, in get\n    response = requests.get(url=address, params=data, headers=header, timeout=timeout)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\api.py\", line 76, in get\n    return request('get', url, params=params, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\adapters.py\", line 529, in send\n    raise ReadTimeout(e, request=request)\n"}, "steps": [{"name": "GET请求接口", "status": "passed", "attachments": [{"name": "请求接口", "source": "4c4fa8e2-07d1-42cf-ab78-6af0036bbaf7-attachment.attach"}, {"name": "请求地址", "source": "7cdadc57-099b-4864-8f99-7180d0d9fc42-attachment.attach"}, {"name": "请求头", "source": "4be85df4-9063-4133-aaf2-dd49da5dfddb-attachment.attach"}, {"name": "请求参数", "source": "3e890890-125e-4eba-aa2f-17530d7ce57d-attachment.attach"}], "start": 1627460018435, "stop": 1627460018457}], "start": 1627460018434, "stop": 1627460038764}], "start": 1627460018434, "stop": 1627460038903}], "start": 1627460018434, "stop": 1627460039214}